// Auto-generated by Uniwind - DO NOT EDIT
// This file will be regenerated when Metro starts

import 'react-native';

declare module 'react-native' {
  interface ViewProps {
    className?: string;
  }

  interface TextProps {
    className?: string;
    selectionColorClassName?: string;
  }

  interface ScrollViewProps {
    className?: string;
    contentContainerClassName?: string;
    endFillColorClassName?: string;
  }

  interface ImageProps {
    className?: string;
    colorClassName?: string;
  }

  interface TextInputProps {
    className?: string;
    cursorColorClassName?: string;
    selectionColorClassName?: string;
    placeholderTextColorClassName?: string;
    selectionHandleColorClassName?: string;
    underlineColorAndroidClassName?: string;
  }

  interface TouchableOpacityProps {
    className?: string;
  }

  interface TouchableHighlightProps {
    className?: string;
    underlayColorClassName?: string;
  }

  interface PressableProps {
    className?: string;
  }

  interface FlatListProps<ItemT> {
    className?: string;
    contentContainerClassName?: string;
    columnWrapperClassName?: string;
    ListFooterComponentClassName?: string;
    ListHeaderComponentClassName?: string;
    endFillColorClassName?: string;
  }

  interface SectionListProps<ItemT, SectionT = unknown> {
    className?: string;
    contentContainerClassName?: string;
    ListFooterComponentClassName?: string;
    ListHeaderComponentClassName?: string;
    endFillColorClassName?: string;
  }

  interface ActivityIndicatorProps {
    className?: string;
    colorClassName?: string;
  }

  interface SwitchProps {
    className?: string;
    thumbColorClassName?: string;
    trackColorOnClassName?: string;
    trackColorOffClassName?: string;
    ios_backgroundColorClassName?: string;
  }

  interface ModalProps {
    className?: string;
    backdropColorClassName?: string;
  }

  interface KeyboardAvoidingViewProps {
    className?: string;
    contentContainerClassName?: string;
  }

  interface ImageBackgroundProps {
    className?: string;
    imageClassName?: string;
    tintColorClassName?: string;
  }

  interface RefreshControlProps {
    className?: string;
    colorClassName?: string;
    tintColorClassName?: string;
    titleColorClassName?: string;
    progressBackgroundColorClassName?: string;
  }

  interface InputAccessoryViewProps {
    className?: string;
    backgroundColorClassName?: string;
  }

  interface SafeAreaViewProps {
    className?: string;
  }

  interface VirtualizedListProps<ItemT> {
    className?: string;
    contentContainerClassName?: string;
    endFillColorClassName?: string;
    ListFooterComponentClassName?: string;
    ListHeaderComponentClassName?: string;
  }
}
